### ISSUE TITLE
Gravestones no longer store items

### ISSUE THREAD

**Issue by BlueIsADude** [PneumonoIsNotAvailable/Gravestones#27] opened 2024-12-23 06:35 UTC
As of the latest version (1.0.10-1.20.1), the gravestones can no longer store any items on death. They can still store XP, but any items in the players inventory are instead dropped on the ground as if the mod wasn't installed.

![2024-12-23_00 19 12](https://github.com/user-attachments/assets/3964f50b-5d23-4b6a-9f24-00c3bedeec19)
An inventory full of netherite leggings, after dying from fall damage

The only other mods installed were mods that Gravestones depends upon (PneumonoCore and Fabric API).

**Comment by PneumonoIsNotAvailable** [comment] 2024-12-23 07:20
Duplicate of #26, version [1.0.11](https://modrinth.com/mod/pneumono_gravestones/version/1.0.11-1.20.1) fixes it :D

**Closed by PneumonoIsNotAvailable** 2024-12-23 07:20 UTC
