### ISSUE TITLE
Doesn't work on server.

### ISSUE THREAD

**Issue by gh0stee56** [PneumonoIsNotAvailable/Gravestones#18] opened 2024-08-02 03:37 UTC
I'm using feather client, and the graves work in single player worlds, but on the server I made the graves aren't working. I'm not sure why. The mods are the same for both instances, so I don't know what the issue is. I am also unsure of where to configure the graves. I was looking through the settings and couldn't seem to find anything.

**Comment by PneumonoIsNotAvailable** [comment] 2024-08-02 07:43
Could you explain what you mean by "not working"? I can't help if I don't understand what the issue is. As for configurations, the mod has built-in [Mod Menu](https://modrinth.com/mod/modmenu) support for a config menu, but if feather client doesn't support that there's always going to the configs folder and editing `gravestones.json` manually. The meanings of each config option are on the [Wiki](https://github.com/PneumonoIsNotAvailable/Gravestones/wiki) if needed.

**Comment by PneumonoIsNotAvailable** [comment] 2024-08-02 07:43
oops didnt mean to close it

**Comment by gh0stee56** [comment] 2024-08-02 20:01
Sorry! I should have been more clear, the actual gravestones don't spawn when I'm on the server, the items still just land on the floor and the XP is lost. But they'll spawn when I'm in a single player world. I just started using Feather last night, so I'm still getting used to it, seems like I can't access the mod files. They aren't there in the regular File Explorer, since they're only being used from the client itself, if that makes sense? I just barely know the basics of using mods, so this is confusing.

**Comment by PneumonoIsNotAvailable** [comment] 2024-08-02 20:52
I'm not really familiar with Feather either, but from a brief look it seems like the mod folder on a Feather server might be in a separate place to your normal mod folder. I think you're right when you say the mods are only on the client, and that's most likely the issue, since Gravestones also needs to be installed server-side to work. Fixing it should be as simple as finding where Feather stores your server (there should be an 'open folder' button or something similar) and copying Gravestones over to there as well. I'm gonna close the issue for now, but if the problems persist and they seem caused by Gravestones, feel free to reply and we can re-open it.

**Closed** 2024-08-02 20:52 UTC
